import { useEffect, useMemo, useRef, useState } from 'react'
import {
  addDirective, approve, bootstrap, createProject, createSession, fetchRoutes, probeSkills,
  runSandbox, searchEvidence, startWorkflow, taskLineage, voiceSocketUrl,
} from './api'

const emptyData = {
  projects: [], runs: [], sessions: [], workflows: [], approvals: [], skills: [], directives: [], audit: [],
  router_configured: false, sandbox: { available: false, models: [] },
  voice: { available: false, transport: 'not_configured', retains_transcripts: false },
}

const nav = [
  ['Delivery', '⌘'], ['Sessions', '◫'], ['Runs', '↗'], ['Routes', '⌁'], ['Approvals', '✓'],
  ['Evidence', '◈'], ['Skills', '✦'], ['Sandbox', '□'],
]

function Mark() { return <span className="brand-mark" aria-hidden="true"><i /><i /><i /></span> }
function Status({ tone = 'green', children }) { return <span className={`status status-${tone}`}><span className="dot" />{children}</span> }
function tone(status) { return ['reconciliation', 'pending', 'not_configured', 'unavailable'].includes(status) ? 'amber' : 'green' }

function Rail({ active, setActive, onNewDelivery, onProfile }) {
  return <aside className="rail">
    <div className="brand"><Mark /><span>Anvil<br /><em>Workbench</em></span></div>
    <nav>{nav.map(([label, glyph]) => <button key={label} aria-label={label} className={active === label ? 'nav-item selected' : 'nav-item'} onClick={() => setActive(label)}><b aria-hidden="true">{glyph}</b>{label}</button>)}</nav>
    <div className="rail-footer"><button className="new-run" onClick={onNewDelivery}><span aria-hidden="true">+</span> New delivery</button><button className="profile" aria-label="Operator menu" onClick={onProfile}><span>AW</span><div><strong>Operator</strong><small>tailnet owner</small></div><b aria-hidden="true">···</b></button></div>
  </aside>
}

function encodePcm16(samples) {
  const bytes = new Uint8Array(samples.length * 2)
  const view = new DataView(bytes.buffer)
  samples.forEach((sample, index) => view.setInt16(index * 2, Math.max(-1, Math.min(1, sample)) * 0x7fff, true))
  let binary = ''
  for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.subarray(index, index + 0x8000))
  return window.btoa(binary)
}

function VoiceDock({ data, append }) {
  const session = data.sessions?.[0]
  const configured = Boolean(data.voice?.available && session)
  const [state, setState] = useState('disconnected')
  const socketRef = useRef(null)
  const captureRef = useRef(null)
  const releaseCapture = () => {
    const capture = captureRef.current
    if (!capture) return
    capture.processor.disconnect(); capture.source.disconnect(); capture.stream.getTracks().forEach((track) => track.stop())
    capture.context.close().catch(() => undefined); captureRef.current = null
  }
  const playAudio = (encoded) => {
    if (typeof encoded !== 'string' || !encoded || !window.AudioContext) return
    try {
      const binary = window.atob(encoded); const context = new window.AudioContext({ sampleRate: 24000 })
      const buffer = context.createBuffer(1, binary.length / 2, 24000); const channel = buffer.getChannelData(0)
      const bytes = new Uint8Array(binary.length); for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index)
      const view = new DataView(bytes.buffer); for (let index = 0; index < channel.length; index += 1) channel[index] = view.getInt16(index * 2, true) / 0x8000
      const source = context.createBufferSource(); source.buffer = buffer; source.connect(context.destination); source.start(); source.onended = () => context.close().catch(() => undefined)
    } catch { append('Voice output could not be played in this browser.') }
  }
  const connect = () => {
    if (!configured) return
    setState('connecting')
    const socket = new WebSocket(voiceSocketUrl(session.id)); socketRef.current = socket
    socket.onopen = () => { socket.send(JSON.stringify({ type: 'session.update', session: { modalities: ['audio', 'text'] } })); setState('ready') }
    socket.onmessage = (event) => { try { const message = JSON.parse(event.data); if (message.type === 'response.output_audio.delta') playAudio(message.delta); if (message.type === 'error') append('Voice relay rejected an event; no delivery action was started.') } catch { append('Voice relay returned an unreadable event; no delivery action was started.') } }
    socket.onclose = () => { releaseCapture(); setState('disconnected') }
    socket.onerror = () => append('Voice relay is unavailable. The session and workflow remain unchanged.')
  }
  const startCapture = async () => {
    if (state !== 'ready' || socketRef.current?.readyState !== WebSocket.OPEN) return
    if (!navigator.mediaDevices?.getUserMedia || !window.AudioContext) { append('This browser cannot capture microphone audio for the Workbench voice relay.'); return }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const context = new window.AudioContext({ sampleRate: 24000 })
      const source = context.createMediaStreamSource(stream); const processor = context.createScriptProcessor(4096, 1, 1)
      processor.onaudioprocess = (event) => { if (socketRef.current?.readyState === WebSocket.OPEN) socketRef.current.send(JSON.stringify({ type: 'input_audio_buffer.append', audio: encodePcm16(event.inputBuffer.getChannelData(0)) })) }
      source.connect(processor); processor.connect(context.destination); captureRef.current = { stream, context, source, processor }; setState('listening')
    } catch { append('Microphone access was not granted. No audio left this browser.') }
  }
  const finishCapture = () => { if (state !== 'listening') return; releaseCapture(); if (socketRef.current?.readyState === WebSocket.OPEN) { socketRef.current.send(JSON.stringify({ type: 'input_audio_buffer.commit' })); socketRef.current.send(JSON.stringify({ type: 'response.create' })) }; setState('ready') }
  const disconnect = () => { releaseCapture(); socketRef.current?.close(); socketRef.current = null; setState('disconnected') }
  return <section className="voice-dock" aria-label="Voice controls"><div><b>Voice, session-bound</b><small>{configured ? 'Push to talk through the private relay; delivery actions still require the bridge.' : 'Configure a private Anvil Voice Realtime endpoint to enable push to talk.'}</small></div>{!configured ? <button disabled aria-label="Voice not configured">Voice unavailable</button> : state === 'disconnected' || state === 'connecting' ? <button onClick={connect} disabled={state === 'connecting'}>{state === 'connecting' ? 'Connecting…' : 'Connect voice'}</button> : <><button className={state === 'listening' ? 'speaking' : ''} onPointerDown={startCapture} onPointerUp={finishCapture} onPointerCancel={finishCapture} aria-label="Hold to talk">{state === 'listening' ? 'Listening… release to send' : 'Hold to talk'}</button><button className="voice-close" onClick={disconnect}>Disconnect</button></>}</section>
}

function Delivery({ data, append, onDirective, onGuide }) {
  const project = data.projects[0]
  const run = data.runs.find((item) => ['queued', 'running'].includes(item.status)) || data.runs[0]
  const session = data.sessions.find((item) => item.id === run?.session_id) || data.sessions[0]
  const messages = (data.directives || []).filter((event) => !session || event.session_id === session.id)
  const [input, setInput] = useState('')
  const submit = async (event) => { event.preventDefault(); if (!session || !input.trim()) return; const text = input.trim(); try { await onDirective(session.id, text); setInput('') } catch { append('Direction was not recorded. No future work packet was changed.') } }
  if (!project) return <main className="delivery empty-delivery"><span className="crumb">Delivery / setup required</span><h1>Start a private delivery</h1><p>Workbench has no synthetic delivery. Create a project, register its local bridge, publish reviewed skills, then create a session.</p><button className="session-action" onClick={onGuide}>Open setup guide</button></main>
  return <main className="delivery"><header className="project-header"><div><span className="crumb">Delivery / {project.name}</span><h1>{run?.task_id ? `Task ${run.task_id}` : 'No active task'}</h1><p>PRD → State plan → local Codex run → evidence → approved PR</p></div><Status tone={run ? tone(run.status) : 'amber'}>{run?.status || 'ready for session'}</Status></header>
    <section className="flow-card"><div className="flow-top"><span className="thread-avatar">A</span><div><strong>Delivery operator</strong><small>{run ? `${run.model} through Anvil Serving` : 'Waiting for a bridge-supervised run'}</small></div><Status tone={run ? tone(run.status) : 'amber'}>{run?.status || 'idle'}</Status></div><ol className="steps"><li className={run ? 'complete' : 'current'}><span>{run ? '✓' : '1'}</span><div><b>{run ? 'State work packet requested' : 'Create a session'}</b><small>{run ? `${run.id} is bound to the bridge and its configured worktree.` : 'A session creates a durable workflow and lease boundary.'}</small></div></li><li className={run?.status === 'evidenced' ? 'complete' : run ? 'current' : ''}><span>{run?.status === 'evidenced' ? '✓' : '2'}</span><div><b>Bridge edits and verifies locally</b><small>Redacted transcripts and State evidence return through the bridge.</small></div></li><li className={run?.status === 'evidenced' ? 'current' : ''}><span>3</span><div><b>Review evidence and authorize a hash-bound action</b><small>GitHub remains local to the bridge and requires approval.</small></div></li></ol></section>
    <section className="conversation" aria-label="Delivery directions">{messages.length ? messages.map((message) => <article className="message human" key={message.id}><div className="message-head"><span>OP</span><b>Recorded direction</b><small>event {message.sequence}</small></div><p>{message.data?.content}</p></article>) : <p className="evidence-empty">No recorded delivery directions for this session yet.</p>}</section>
    <form className="composer" onSubmit={submit}><textarea aria-label="Add direction to this delivery" value={input} disabled={!session} onChange={(event) => setInput(event.target.value)} rows="2" placeholder={session ? 'Add a direction for the next work packet…' : 'Create a session before adding delivery direction…'} /><div><small>Saved into the next bridge work packet; it does not interrupt a running Codex process.</small><button type="submit" disabled={!session || !input.trim()} aria-label="Send delivery direction">Send <span aria-hidden="true">↵</span></button></div></form><VoiceDock data={data} append={append} />
  </main>
}

function Trace({ data, setActive, append, refresh, selectedApprovalId, clearApproval }) {
  const run = data.runs[0]; const approval = data.approvals.find((item) => item.id === selectedApprovalId && item.status === 'pending'); const [expanded, setExpanded] = useState(false); const [busy, setBusy] = useState(false)
  const authorize = async () => { if (!approval) return; setBusy(true); try { await approve(approval.id); clearApproval(); append('Approval recorded. The local bridge may consume this exact action once.'); await refresh() } catch { append('Approval was not recorded. The bridge remains unable to create a PR.') } finally { setBusy(false) } }
  return <aside className="trace"><section className="trace-head"><div><span>Live trace</span><Status tone={data.router_configured ? 'green' : 'amber'}>{data.router_configured ? 'router configured' : 'router unavailable'}</Status></div><button aria-label="Show correlation trace" aria-expanded={expanded} onClick={() => setExpanded(!expanded)}>{expanded ? '−' : '↗'}</button></section><section className="trace-body"><TraceStep label="Intent" value={run?.task_id || 'No task selected'} detail={run ? `run ${run.id}` : 'Start a session to request a State work packet.'} done={Boolean(run)} /><TraceStep label="Route" value={run?.model || 'No route selected'} detail={data.router_configured ? 'decision lookup is available in Routes' : 'router token or URL is missing'} done={Boolean(run && data.router_configured)} /><TraceStep label="Skills" value={data.skills?.length ? `${data.skills.length} bridge-published` : 'No skills published'} detail="Only selected local skills enter a work packet." done={Boolean(data.skills?.length)} /><TraceStep label="Verify" value={run?.status === 'evidenced' ? 'evidence submitted' : 'independent gate pending'} detail="The bridge submits evidence to State before approval." current={run?.status !== 'evidenced'} />{expanded && <div className="raw-trace"><code>workbench_run_id: {run?.id || 'not assigned'}</code><code>task_id: {run?.task_id || 'not assigned'}</code><code>request_id: written by Serving if the model request succeeds</code></div>}</section><section className="evidence-mini"><header><span>Evidence packet</span><button onClick={() => setActive('Evidence')}>View all</button></header><p className="evidence-empty">{run?.status === 'evidenced' ? 'Use Evidence search to inspect cited, redacted artifacts.' : 'Awaiting independent bridge evidence.'}</p></section><section className="approval-card"><div className="approval-title"><span>Approval</span><Status tone={approval ? 'amber' : 'green'}>{approval ? 'selected' : 'selection required'}</Status></div><h2>{approval ? approval.action_type.replaceAll('_', ' ') : 'Select an approval to review'}</h2>{approval ? <><dl className="approval-binding"><div><dt>Approval id</dt><dd>{approval.id}</dd></div><div><dt>Payload hash</dt><dd>{approval.payload_hash}</dd></div><div><dt>Run</dt><dd>{approval.payload?.run_id || 'not bound'}</dd></div><div><dt>Worktree</dt><dd>{approval.payload?.worktree_id || 'not bound'}</dd></div></dl><pre aria-label="Selected approval payload">{JSON.stringify(approval.payload, null, 2)}</pre></> : <p>Open Approvals and choose one pending action. Workbench never guesses which grant you intended.</p>}<p className="muted">Approval is a one-time release; the bridge checks this exact safe payload and binding before it can change GitHub.</p><button disabled={busy || !approval} onClick={authorize}>{busy ? 'Authorizing…' : 'Authorize selected action'} <span aria-hidden="true">→</span></button></section></aside>
}

function TraceStep({ label, value, detail, done, current }) { return <div className={`trace-step ${done ? 'done' : ''} ${current ? 'current' : ''}`}><i>{done ? '✓' : current ? '●' : '○'}</i><div><small>{label}</small><b>{value}</b><span>{detail}</span></div></div> }

function SessionsView({ data, onNewSession, onStartSession }) { const sessions = data.sessions || []; const workflows = data.workflows || []; return <section className="workspace-view"><span className="crumb">Sessions / durable harness contexts</span><div className="view-heading"><div><h1>Concurrent sessions</h1><p>Each session has its own workflow cursor. Worktree leases prevent concurrent sessions from editing the same configured worktree.</p></div><button className="session-action" onClick={onNewSession} disabled={!data.projects[0]}>New concurrent session</button></div><div className="session-list">{sessions.length ? sessions.map((session) => { const workflow = workflows.find((item) => item.session_id === session.id); const activeRun = data.runs?.some((run) => run.session_id === session.id && ['queued', 'running'].includes(run.status)); return <article key={session.id}><div><b>{session.title}</b><small>{session.worktree_id} · {session.id}</small></div><span>{workflow ? `workflow v${workflow.version} · ${workflow.status}` : 'workflow pending'}</span><Status tone={activeRun ? 'green' : tone(workflow?.status)}>{activeRun ? 'active run' : session.status}</Status><button aria-label={`Start delivery ${session.title}`} disabled={!workflow || activeRun || workflow.status !== 'draft'} onClick={() => onStartSession(session, workflow)}>Start delivery</button></article> }) : <article className="session-empty"><b>No harness session yet</b><span>Create a project and bridge, then create a session.</span></article>}</div></section> }

function RunsView({ data, refresh }) { return <section className="workspace-view"><span className="crumb">Runs / bridge-supervised</span><div className="view-heading"><div><h1>Runs</h1><p>Every row is a durable Workbench run, correlated to a State task and selected model.</p></div><button className="session-action" onClick={refresh}>Refresh runs</button></div><div className="data-list">{data.runs.length ? data.runs.map((run) => <article key={run.id}><b>{run.task_id || 'Unassigned task'}</b><span>{run.model} · {run.id}</span><Status tone={tone(run.status)}>{run.status}</Status></article>) : <article><b>No delivery runs yet</b><span>Start a session workflow to create a bridge command.</span><Status tone="amber">idle</Status></article>}</div></section> }

function RoutesView({ data, append }) { const [routes, setRoutes] = useState([]); const [loaded, setLoaded] = useState(false); const [busy, setBusy] = useState(false); const refresh = async () => { setBusy(true); try { const value = await fetchRoutes(); setRoutes(value.routes || []); setLoaded(true) } catch { append('Route decisions are unavailable. Check the server-held Anvil Serving URL and token.') } finally { setBusy(false) } }; return <section className="workspace-view"><span className="crumb">Routes / Anvil Serving</span><div className="view-heading"><div><h1>Routes</h1><p>Read-only router decision metadata, filtered to Workbench run correlations.</p></div><button className="session-action" onClick={refresh} disabled={!data.router_configured || busy}>{busy ? 'Refreshing…' : 'Refresh decisions'}</button></div>{!data.router_configured ? <div className="sandbox-note"><b>Routes unavailable</b><span>Configure the hub’s Anvil Serving URL and token. The browser never sees either credential.</span></div> : <div className="data-list">{loaded && !routes.length ? <article><b>No correlated decisions yet</b><span>Run a bridge delivery, then refresh after Serving records the request.</span><Status tone="amber">waiting</Status></article> : routes.map((route, index) => <article key={`${route.request_id || index}`}><b>{route.intent || route.model || route.served_model || route.served_tier || 'selected route'}</b><span>{route.workbench_run_id} · {route.task_id || 'no task id'} · {route.request_id || 'no request id'}</span><Status>{route.status || route.tier || route.served_tier || 'recorded'}</Status></article>)}</div>}</section> }

function ApprovalsView({ data, selectApproval }) { const pending = data.approvals.filter((approval) => approval.status === 'pending'); return <section className="workspace-view"><span className="crumb">Approvals / hash-bound</span><h1>Approvals</h1><p>Approval only releases a matching, one-time bridge command; it does not expose a GitHub credential to this browser.</p><div className="data-list">{pending.length ? pending.map((approval) => <article key={approval.id}><b>{approval.action_type.replaceAll('_', ' ')}</b><span>{approval.id} · {approval.payload_hash}</span><button className="inline-action" aria-label={`Review action ${approval.id}`} onClick={() => selectApproval(approval.id)}>Review action</button></article>) : <article><b>No pending approval</b><span>A bridge must submit evidence before a PR action can be requested.</span><Status tone="amber">waiting</Status></article>}</div></section> }

function EvidenceView({ data, append }) { const [query, setQuery] = useState(''); const [results, setResults] = useState([]); const [lineage, setLineage] = useState(null); const project = data.projects[0]; const search = async (event) => { event.preventDefault(); if (!project || !query.trim()) return; try { const value = await searchEvidence(project.id, query.trim()); setResults(value.results || []); setLineage(null) } catch { append('Evidence search is unavailable. The graph remains read-only and never approves actions.') } }; const loadLineage = async (taskId) => { try { setLineage(await taskLineage(taskId)) } catch { append('Task lineage is unavailable for that task.') } }; return <section className="workspace-view"><span className="crumb">Evidence / redacted projection</span><h1>Evidence</h1><p>Searches the read-optimized evidence projection. Anvil State remains canonical for task acceptance.</p><form className="query-form" onSubmit={search}><input aria-label="Evidence query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search evidence and cited artifacts" disabled={!project} /><button disabled={!project || !query.trim()}>Search evidence</button></form><div className="data-list">{results.map((result, index) => <article key={`${result.citation || index}`}><b>{result.title || result.source_id || 'Evidence artifact'}</b><span>{result.citation || result.summary || 'redacted projection result'}</span><Status>cited</Status></article>)}{!results.length && <article><b>No evidence query yet</b><span>Search only returns redacted, cited projection records.</span><Status tone="amber">ready</Status></article>}</div>{data.runs.filter((run) => run.task_id).slice(0, 4).map((run) => <button className="lineage-button" key={run.id} onClick={() => loadLineage(run.task_id)}>Show lineage for {run.task_id}</button>)}{lineage && <pre className="lineage-result">{JSON.stringify(lineage, null, 2)}</pre>}</section> }

function SkillsView({ data, append, refresh }) { const project = data.projects[0]; const [busy, setBusy] = useState(false); const verify = async () => { if (!project) return; setBusy(true); try { await probeSkills(project.id); append('Bridge skill check queued. The bridge verifies local files and matching digests before it reports evidence.'); await refresh() } catch { append('Skills could not be checked. A project bridge must publish configured skill metadata first.') } finally { setBusy(false) } }; return <section className="workspace-view"><span className="crumb">Skills / bridge-local</span><div className="view-heading"><div><h1>Reviewed skills</h1><p>Skills are discovered from explicit local bridge roots. The hub receives only names, descriptions, and digests; paths and bodies stay local.</p></div><button className="session-action" onClick={verify} disabled={!project || !data.skills.length || busy}>{busy ? 'Queueing check…' : 'Verify bridge skills'}</button></div><div className="data-list">{data.skills.length ? data.skills.map((skill) => <article key={`${skill.bridge_id}:${skill.skill_id}`}><b>{skill.skill_id}</b><span>{skill.description} · {skill.content_sha256.slice(0, 12)}…</span><Status>published</Status></article>) : <article><b>No skills published</b><span>Start the local bridge with one or more explicit <code>--skills-root</code> paths.</span><Status tone="amber">bridge setup</Status></article>}</div></section> }

function SandboxView({ data, append }) { const [model, setModel] = useState(data.sandbox?.models?.[0] || ''); const [input, setInput] = useState(''); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); useEffect(() => { setModel(data.sandbox?.models?.[0] || '') }, [data.sandbox]); const submit = async (event) => { event.preventDefault(); setBusy(true); try { setResult(await runSandbox({ model, input })) } catch { append('Sandbox request was not accepted by Anvil Serving. No provider fallback was used.') } finally { setBusy(false) } }; return <section className="workspace-view"><span className="crumb">Sandbox / Serving only</span><h1>Model sandbox</h1><p>A bounded, audited Responses request through Anvil Serving. It is separate from bridge delivery and cannot create a PR, merge, or change policy.</p>{!data.sandbox?.available ? <div className="sandbox-note"><b>Sandbox unavailable</b><span>Set an allowlisted <code>WORKBENCH_SANDBOX_MODELS</code> value plus the hub’s Serving URL and token.</span></div> : <form className="sandbox-form" onSubmit={submit}><label>Allowed route<select aria-label="Sandbox model" value={model} onChange={(event) => setModel(event.target.value)}>{data.sandbox.models.map((item) => <option key={item}>{item}</option>)}</select></label><label>Prompt<textarea aria-label="Sandbox prompt" value={input} onChange={(event) => setInput(event.target.value)} rows="5" placeholder="Ask a bounded, non-mutating model question" /></label><button disabled={busy || !input.trim()}>{busy ? 'Routing…' : 'Run through Anvil Serving'}</button></form>}{result && <section className="sandbox-result"><b>{result.model} · {result.status}</b><pre>{result.output_text || 'The routed response contained no output_text.'}</pre></section>}</section> }

function WorkspaceView({ active, data, onNewSession, onStartSession, append, refresh, selectApproval }) { if (active === 'Sessions') return <SessionsView data={data} onNewSession={onNewSession} onStartSession={onStartSession} />; if (active === 'Runs') return <RunsView data={data} refresh={refresh} />; if (active === 'Routes') return <RoutesView data={data} append={append} />; if (active === 'Approvals') return <ApprovalsView data={data} selectApproval={selectApproval} />; if (active === 'Evidence') return <EvidenceView data={data} append={append} />; if (active === 'Skills') return <SkillsView data={data} append={append} refresh={refresh} />; return <SandboxView data={data} append={append} /> }

function Modal({ title, children, onClose }) { return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button aria-label={`Close ${title}`} onClick={onClose}>×</button></header>{children}</section></div> }

function NewDelivery({ onClose, onCreate }) { const [name, setName] = useState(''); const [stateRoot, setStateRoot] = useState('.anvil'); const [busy, setBusy] = useState(false); const submit = async (event) => { event.preventDefault(); if (!name.trim()) return; setBusy(true); try { await onCreate({ name: name.trim(), state_root: stateRoot.trim() || '.anvil' }) } finally { setBusy(false) } }; return <Modal title="New delivery" onClose={onClose}><p>This creates a Workbench project record only. Register a project-local bridge separately; its secret never enters this browser.</p><form className="modal-form" onSubmit={submit}><label>Project name<input aria-label="Project name" value={name} onChange={(event) => setName(event.target.value)} /></label><label>State root<input aria-label="State root" value={stateRoot} onChange={(event) => setStateRoot(event.target.value)} /></label><div><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" disabled={busy || !name.trim()}>{busy ? 'Creating…' : 'Create project'}</button></div></form></Modal> }

function NewSession({ project, skills, onClose, onCreate }) { const [title, setTitle] = useState(''); const [worktree, setWorktree] = useState('default'); const [selected, setSelected] = useState([]); const [busy, setBusy] = useState(false); const toggle = (skill) => setSelected((current) => current.includes(skill) ? current.filter((item) => item !== skill) : [...current, skill]); const submit = async (event) => { event.preventDefault(); if (!project || !title.trim() || !worktree.trim()) return; setBusy(true); try { await onCreate({ project_id: project.id, title: title.trim(), worktree_id: worktree.trim(), skills: selected }) } finally { setBusy(false) } }; return <Modal title="New concurrent session" onClose={onClose}><p>A session is a durable harness context. Its worktree id must match a local bridge configuration before delivery can start.</p><form className="modal-form" onSubmit={submit}><label>Session title<input aria-label="Session title" value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Configured worktree id<input aria-label="Configured worktree id" value={worktree} onChange={(event) => setWorktree(event.target.value)} /></label>{skills.length ? <fieldset className="skill-selector"><legend>Bridge-published skills for this session</legend>{skills.map((skill) => <label key={skill.skill_id}><input type="checkbox" checked={selected.includes(skill.skill_id)} onChange={() => toggle(skill.skill_id)} />{skill.skill_id}</label>)}</fieldset> : null}<div><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" disabled={busy || !project || !title.trim() || !worktree.trim()}>{busy ? 'Creating…' : 'Create session'}</button></div></form></Modal> }

function StartSession({ session, workflow, onClose, onStart }) { const [taskId, setTaskId] = useState(''); const [model, setModel] = useState('planning'); const [busy, setBusy] = useState(false); const submit = async (event) => { event.preventDefault(); if (!taskId.trim()) return; setBusy(true); try { await onStart(workflow.id, { task_id: taskId.trim(), model: model.trim() || 'planning' }) } finally { setBusy(false) } }; return <Modal title={`Start ${session.title}`} onClose={onClose}><p>This queues the workflow’s pinned agent step through the configured local bridge. State claims the task; the browser never selects a filesystem path.</p><form className="modal-form" onSubmit={submit}><label>State task id<input aria-label="State task id" value={taskId} onChange={(event) => setTaskId(event.target.value)} /></label><label>Requested route<input aria-label="Requested route" value={model} onChange={(event) => setModel(event.target.value)} /></label><div><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button type="submit" disabled={busy || !taskId.trim()}>{busy ? 'Starting…' : 'Start bridge delivery'}</button></div></form></Modal> }

function Onboarding({ data, onClose, setActive, onNewDelivery, onNewSession }) { const project = data.projects[0]; const steps = [{ label: 'Create a Workbench project', complete: Boolean(project), action: () => project ? setActive('Delivery') : onNewDelivery() }, { label: 'Register a project-local bridge', complete: Boolean(project?.bridge_id), action: () => setActive('Skills') }, { label: 'Publish and verify bridge skills', complete: Boolean(data.skills?.length), action: () => setActive('Skills') }, { label: 'Create a harness session', complete: Boolean(data.sessions?.length), action: () => onNewSession() }, { label: 'Run a State task through the bridge', complete: Boolean(data.runs?.length), action: () => setActive('Sessions') }, { label: 'Review evidence before an approval', complete: Boolean(data.runs?.some((run) => run.status === 'evidenced')), action: () => setActive('Evidence') }]; const current = steps.find((step) => !step.complete) || steps.at(-1); const go = () => { current.action(); onClose() }; return <Modal title="Workbench setup guide" onClose={onClose}><p>This guide reflects live hub state. It never marks a bridge, skill, run, or evidence step complete on its own.</p><ol className="onboarding-steps">{steps.map((step, index) => <li key={step.label} className={step.complete ? 'done' : ''}><span>{step.complete ? '✓' : index + 1}</span>{step.label}</li>)}</ol><button className="session-action" onClick={go}>{current.complete ? 'Review completed setup' : `Continue: ${current.label}`}</button></Modal> }

function Notifications({ audit, read, onRead }) { return <section className="notifications" aria-label="Notifications"><header><b>Recent hub activity</b><button onClick={onRead}>Mark viewed</button></header>{read ? <p>All current activity is marked viewed in this browser.</p> : audit.length ? audit.slice(0, 4).map((event) => <p key={event.id}><b>{event.kind}</b><br />{event.actor}</p>) : <p>No Workbench audit events yet.</p>}</section> }
function ProfileMenu({ data, onClose }) { return <section className="profile-menu" aria-label="Operator menu"><b>{data.actor || 'Allowlisted operator'}</b><span>Tailnet identity verified by the hub</span><small>Project creation and approvals are server-checked. The browser has no bridge, GitHub, or model credential.</small><button onClick={onClose}>Close menu</button></section> }

function App() {
  const [active, setActive] = useState('Delivery'); const [data, setData] = useState(emptyData); const [notice, setNotice] = useState(''); const [selectedApprovalId, setSelectedApprovalId] = useState(null); const [newDeliveryOpen, setNewDeliveryOpen] = useState(false); const [newSessionOpen, setNewSessionOpen] = useState(false); const [startSession, setStartSession] = useState(null); const [guideOpen, setGuideOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); const [notificationsOpen, setNotificationsOpen] = useState(false); const [notificationsRead, setNotificationsRead] = useState(false)
  const load = async () => { const value = await bootstrap(); setData({ ...emptyData, ...value, sandbox: { ...emptyData.sandbox, ...(value.sandbox || {}) }, voice: { ...emptyData.voice, ...(value.voice || {}) } }); return value }
  useEffect(() => { load().catch(() => setNotice('Workbench hub is unavailable; no local mock delivery is shown.')) }, [])
  const createDelivery = async (payload) => { try { const project = await createProject(payload); setData((current) => ({ ...current, projects: [project, ...current.projects] })); setNewDeliveryOpen(false); setNotice(`Created ${project.name}. Register its bridge locally before starting a run.`); await load() } catch { setNotice('Project could not be created. No bridge or run was started.') } }
  const createConcurrentSession = async (payload) => { try { const created = await createSession(payload); setData((current) => ({ ...current, sessions: [created.session, ...current.sessions], workflows: [created.workflow, ...current.workflows] })); setNewSessionOpen(false); setActive('Sessions'); setNotice(`Created ${created.session.title}. Start it only after its named worktree is configured on the bridge.`); await load() } catch { setNotice('Session could not be created. No bridge run was started.') } }
  const startConcurrentSession = async (workflowId, payload) => { try { const result = await startWorkflow(workflowId, payload); setStartSession(null); setActive('Delivery'); setNotice(`Started ${payload.task_id} through the local bridge. The workflow is traceable in this session.`); setData((current) => ({ ...current, runs: [result.run, ...current.runs] })); await load() } catch { setNotice('Workflow did not start. Check the project bridge, published skills, and named worktree configuration.') } }
  const addDirection = async (sessionId, text) => { const event = await addDirective(sessionId, text); setData((current) => ({ ...current, directives: [...current.directives, event] })); setNotice('Direction recorded. It will be included only in the next bridge work packet for this session.'); await load() }
  const context = useMemo(() => active === 'Delivery' ? 'Delivery cockpit' : `${active} view`, [active])
  const selectApproval = (approvalId) => { setSelectedApprovalId(approvalId); setActive('Delivery') }
  return <div className="app-shell">
    <Rail active={active} setActive={setActive} onNewDelivery={() => setNewDeliveryOpen(true)} onProfile={() => setProfileOpen(!profileOpen)} />
    {profileOpen && <ProfileMenu data={data} onClose={() => setProfileOpen(false)} />}
    <div className="workspace"><header className="topbar"><span>{context}</span><div><Status tone={data.router_configured ? 'green' : 'amber'}>{data.router_configured ? 'router configured' : 'router not configured'}</Status><button className="help" aria-label="Help" onClick={() => setGuideOpen(true)}>?</button><button className="bell" aria-label="Notifications" aria-expanded={notificationsOpen} onClick={() => setNotificationsOpen(!notificationsOpen)}>♢</button></div></header>
      {notificationsOpen && <Notifications audit={data.audit || []} read={notificationsRead} onRead={() => setNotificationsRead(true)} />}
      <div className="main-grid">
        {active === 'Delivery' ? <Delivery data={data} append={setNotice} onDirective={addDirection} onGuide={() => setGuideOpen(true)} /> : <WorkspaceView active={active} data={data} onNewSession={() => setNewSessionOpen(true)} onStartSession={(session, workflow) => setStartSession({ session, workflow })} append={setNotice} refresh={load} selectApproval={selectApproval} />}
        <Trace data={data} setActive={setActive} append={setNotice} refresh={load} selectedApprovalId={selectedApprovalId} clearApproval={() => setSelectedApprovalId(null)} />
      </div>
      {notice && <div className="toast" role="status">{notice}<button aria-label="Dismiss notification" onClick={() => setNotice('')}>×</button></div>}
    </div>
    {newDeliveryOpen && <NewDelivery onClose={() => setNewDeliveryOpen(false)} onCreate={createDelivery} />}
    {newSessionOpen && <NewSession project={data.projects[0]} skills={data.skills.filter((skill) => skill.bridge_id === data.projects[0]?.bridge_id)} onClose={() => setNewSessionOpen(false)} onCreate={createConcurrentSession} />}
    {startSession && <StartSession session={startSession.session} workflow={startSession.workflow} onClose={() => setStartSession(null)} onStart={startConcurrentSession} />}
    {guideOpen && <Onboarding data={data} onClose={() => setGuideOpen(false)} setActive={setActive} onNewDelivery={() => setNewDeliveryOpen(true)} onNewSession={() => setNewSessionOpen(true)} />}
  </div>
}

export default App
